name: Prepare Release

on:
  push:
    tags: ["*"]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run: Only log actions, do not push or create GitHub Release.'
        required: true
        type: boolean
        default: true

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ github.ref_name }}
      DATE: $(date +"%Y-%m-%d")
    steps:
      - run: echo "🎫 A new tag=${{ github.ref_name }} has been created!"

      - name: Get the release version
        run: echo "Running prep-release for version ${{ env.VERSION }}"
#        run: echo ::set-output name=VERSION::${{ github.ref_name }}

      - name: Get the current date
#        run: echo "Today's date ${{ env.DATE }}"
        id: get_date
#        run: echo $(date +"%Y-%m-%d") | { var=$(cat); echo ::set-output name=VERSION::"${var}"; }
        run: echo "::set-output name=DATE::$(date +'%Y-%m-%d')"

      - name: Welcome message
        run: echo "Preparing a new release for version ${{ env.VERSION }} on ${{ steps.get_date.outputs.DATE }}

      - uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned"

      - run: echo "Authenticating with GitHub"
      - name: Authenticate email
        run: git config user.email "ivangb6@gmail.com"
      - name: Authenticate name
        run: git config user.name "Ivan Garza Bermea"

      - run: echo "Setting up JDK"
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - run: echo "🖥️ The workflow is now ready to test your code"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create new tag
        run: git tag -a ${{ env.VERSION }} -m "Tagged release ${{ env.VERSION }} on ${{ env.DATE }}"

      - name: Push new tag to origin
        if: ${{ !inputs.dry_run }}
        run: git push origin ${{ env.VERSION }}

      - run: echo "Creating new GitHub Release for version ${{ env.VERSION }}"
        if: ${{ !inputs.dry_run }}

      - name: Create new GitHub Release
        if: ${{ !inputs.dry_run }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

#  jitpack:
#    runs-on: ubuntu-latest
#    needs: github-release
#    steps:
#      - name: Welcome message
#        run: echo "Triggering jitpack master-SNAPSHOT for further use"
#      - name: Request master-SNAPSHOT from JitPack
#        if: ${{ !inputs.dry_run }}
#        run: |
#          # timeout in 30 seconds to avoid waiting for build
#          curl -s -m 30 https://jitpack.io/com/ivangarzab/composable-webview/master-SNAPSHOT/ || true